steps:
- task: SDLNativeRules@2
  displayName: 'Run the PREfast SDL Native Rules for MSBuild'
  inputs:
    userProvideBuildInfo: 'auto'
  continueOnError: true

- task: CredScan@2
  displayName: 'Run CredScan'
  inputs:
    debugMode: false
  continueOnError: true

- task: BinSkim@3
  displayName: 'Run BinSkim'
  inputs:
    arguments: 'analyze $(Build.BinariesDirectory)\RelWithDebInfo\*.dll  --recurse --verbose'
  continueOnError: true

- task: PublishSecurityAnalysisLogs@2
  displayName: 'Publish Security Analysis Logs'
  continueOnError: true

