jobs:
- template: templates/linux-ci.yml
  parameters:
    AgentPool : 'Linux-CPU'
    JobName: 'Linux_CI_Dev_x86'
    BuildCommand: 'tools/ci_build/github/linux/run_dockerbuild.sh -o ubuntu16.04 -d cpu -r $(Build.BinariesDirectory) -a x86 -x "--x86"'
    DoNugetPack:  'false'
    ArtifactName: 'drop-linux-x86'
