# Defined as pipeline variables
# variables:
#   AgentPoolWin : 'Win-CPU'
#   AgentPoolLinux : 'Linux-CPU'
#   AgentPoolMacOS : 'macOS-10.13'

variables:
  PackageName: 'Microsoft.ML.OnnxRuntime.MKLML'

jobs: 
- template: templates/cpu-mklml.yml
  parameters:
    AgentPool : $(AgentPoolWin)
    DoEsrp: 'false'
