# Defined as pipeline variables
# variables:
#   AgentPoolWin : 'Win-CPU'
#   AgentPoolLinux : 'Linux-CPU'
#   AgentPoolMacOS : 'macOS-10.13'

schedules:
- cron: "0 12 * * *"
  displayName: Daily Build
  branches:
    include:
    - master
  always: true

variables:
  DisableContribOps: 'ON'

jobs: 
- template: templates/cpu-nocontribops.yml
  parameters:
    AgentPool : $(AgentPoolWin)
    DoEsrp: 'true'
